import { invoke } from "@tauri-apps/api/core";

/**
 * Centralised thumbnail loader. Limits concurrent Rust invocations so that
 * opening a large folder of big images does not flood the backend with
 * `spawn_blocking` jobs (each decoding multi-MB files). Also caches results
 * so re-visiting a folder is instant.
 */

const MAX_CONCURRENT = Math.min(
  8,
  Math.max(4, navigator.hardwareConcurrency ?? 4)
);

const CACHE_LIMIT = 500;

type Job = {
  path: string;
  cancelled: boolean;
  resolve: (value: string) => void;
  reject: (err: unknown) => void;
};

const cache = new Map<string, string>(); // path -> base64
const inflight = new Map<string, Promise<string>>();
const queue: Job[] = [];
let active = 0;

function rememberInCache(path: string, b64: string) {
  if (cache.has(path)) cache.delete(path);
  cache.set(path, b64);
  while (cache.size > CACHE_LIMIT) {
    const oldest = cache.keys().next().value;
    if (oldest === undefined) break;
    cache.delete(oldest);
  }
}

function pump() {
  while (active < MAX_CONCURRENT && queue.length > 0) {
    const job = queue.shift()!;
    if (job.cancelled) {
      job.reject(new DOMException("cancelled", "AbortError"));
      continue;
    }
    active += 1;
    invoke<string>("get_thumbnail", { photoPath: job.path })
      .then((b64) => {
        rememberInCache(job.path, b64);
        if (!job.cancelled) job.resolve(b64);
        else job.reject(new DOMException("cancelled", "AbortError"));
      })
      .catch((err) => job.reject(err))
      .finally(() => {
        active -= 1;
        inflight.delete(job.path);
        pump();
      });
  }
}

export interface ThumbnailHandle {
  promise: Promise<string>;
  cancel(): void;
}

export function requestThumbnail(path: string): ThumbnailHandle {
  const cached = cache.get(path);
  if (cached !== undefined) {
    // Refresh LRU position.
    rememberInCache(path, cached);
    return { promise: Promise.resolve(cached), cancel: () => {} };
  }

  const existing = inflight.get(path);
  if (existing) {
    return { promise: existing, cancel: () => {} };
  }

  let job!: Job;
  const promise = new Promise<string>((resolve, reject) => {
    job = { path, cancelled: false, resolve, reject };
    queue.push(job);
  });
  inflight.set(path, promise);
  pump();

  return {
    promise,
    cancel: () => {
      job.cancelled = true;
    },
  };
}

export function isCancellation(err: unknown): boolean {
  return err instanceof DOMException && err.name === "AbortError";
}

// ---------------------------------------------------------------------------
// Batch prefetching + progress
// ---------------------------------------------------------------------------

export interface ThumbnailBatchProgress {
  /** Monotonic id of the active batch. 0 means "no active batch". */
  batchId: number;
  total: number;
  loaded: number;
  failed: number;
  /** True while there is still work outstanding for the current batch. */
  inProgress: boolean;
}

const progressTarget = new EventTarget();
let progressState: ThumbnailBatchProgress = {
  batchId: 0,
  total: 0,
  loaded: 0,
  failed: 0,
  inProgress: false,
};

let nextBatchId = 1;
/** Handles for the currently-active batch so it can be cancelled. */
let activeBatchHandles: ThumbnailHandle[] = [];

function emitProgress() {
  progressTarget.dispatchEvent(
    new CustomEvent<ThumbnailBatchProgress>("progress", {
      detail: { ...progressState },
    })
  );
}

export function getThumbnailProgress(): ThumbnailBatchProgress {
  return { ...progressState };
}

export function onThumbnailProgress(
  listener: (state: ThumbnailBatchProgress) => void
): () => void {
  const handler = (e: Event) => {
    listener((e as CustomEvent<ThumbnailBatchProgress>).detail);
  };
  progressTarget.addEventListener("progress", handler);
  return () => progressTarget.removeEventListener("progress", handler);
}

/**
 * Start prefetching thumbnails for `paths` in the order given. Replaces any
 * currently-active batch. Returns the new batch id. Subsequent UI requests
 * for the same paths will dedupe against the in-flight prefetch (so on-screen
 * cards render as soon as their thumbnail has been generated by the batch).
 */
export function startThumbnailBatch(paths: string[]): number {
  // Cancel any previous batch so its outstanding (queued, not yet running)
  // jobs stop tying up the worker pool.
  for (const h of activeBatchHandles) h.cancel();
  activeBatchHandles = [];

  const batchId = nextBatchId++;
  progressState = {
    batchId,
    total: paths.length,
    loaded: 0,
    failed: 0,
    inProgress: paths.length > 0,
  };
  emitProgress();

  if (paths.length === 0) return batchId;

  const handles: ThumbnailHandle[] = [];
  for (const path of paths) {
    const handle = requestThumbnail(path);
    handles.push(handle);
    handle.promise.then(
      () => {
        if (progressState.batchId !== batchId) return;
        progressState = {
          ...progressState,
          loaded: progressState.loaded + 1,
        };
        finalizeIfDone(batchId);
        emitProgress();
      },
      (err) => {
        if (progressState.batchId !== batchId) return;
        if (isCancellation(err)) return;
        progressState = {
          ...progressState,
          failed: progressState.failed + 1,
        };
        finalizeIfDone(batchId);
        emitProgress();
      }
    );
  }
  activeBatchHandles = handles;
  return batchId;
}

function finalizeIfDone(batchId: number) {
  if (progressState.batchId !== batchId) return;
  const done = progressState.loaded + progressState.failed;
  if (done >= progressState.total) {
    progressState = { ...progressState, inProgress: false };
  }
}

/** Cancel the active batch (if any) and reset progress to idle. */
export function clearThumbnailBatch() {
  for (const h of activeBatchHandles) h.cancel();
  activeBatchHandles = [];
  progressState = {
    batchId: 0,
    total: 0,
    loaded: 0,
    failed: 0,
    inProgress: false,
  };
  emitProgress();
}
